server:
  port: 8082
  forward-headers-strategy: framework
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

#Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
  api-docs:
    path: /api-docs
