server:
  port: 8082
spring:
  kafka:
    producer:
      bootstrap-servers: kata-kafka:29092
    consumer:
      bootstrap-servers: kata-kafka:29092
      group-id: my-first-group

#Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
  api-docs:
    path: /api-docs
